### ISSUE TITLE
Rewrite querying in query-convert.js for convertTerm 

### ISSUE THREAD

**Issue by dzhou343** [Holmusk/HolmuskDB#36]
When trying to convertTerm in query-convert.js, if the term is something like a number, an error is raised as neo4j expects a variable. This issue was uncovered in the #34 

Below is the error dump for easy reference: 

```
(node:6701) UnhandledPromiseRejectionWarning: Neo4jError: Invalid input '8': expected whitespace, a variable, node labels, a property map, ')' or PatternElement (line 2, column 9 (offset: 47))
"CREATE (80008000:handphone:contact:number {value: '80008000'})"
         ^

    at captureStacktrace (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/result.js:263:15)
    at new Result (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/result.js:68:19)
    at newCompletedResult (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/transaction.js:449:10)
    at Object.run (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/transaction.js:287:14)
    at Transaction.run (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/transaction.js:123:32)
    at /home/daniel/HolmuskDB/backend/src/db-utils.js:21:54
    at TransactionExecutor._safeExecuteTransactionWork (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/internal/transaction-executor.js:134:22)
    at TransactionExecutor._executeTransactionInsidePromise (/home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/internal/transaction-executor.js:122:32)
    at /home/daniel/HolmuskDB/backend/node_modules/neo4j-driver/lib/internal/transaction-executor.js:61:15
    at new Promise (<anonymous>)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

This occurs on the following JSON Post request body input: 

```
{ "type" : "create"
, "name" : "Jonas"
, "details" : [ { "relations" : []
                , "term" : 80008000
                , "labels" : ["handphone", "contact", "number"]
                }
              , { "relations" : ["From"]
                , "term" : "ABC Group"
                , "labels" : ["Company"]
                }
              ]
}
```

**Comment by dzhou343** [comment]
Issue fixed by validation step implemented as described in issue #45
